### ISSUE TITLE
update to bevy 0.5

### ISSUE THREAD

**Issue by phrohdoh** [carrascomj/bevy_svg_map#11]
https://bevyengine.org/learn/book/migration-guides/0.4-0.5

**Comment by carrascomj** [comment]
Thanks, taryn!

I have this repo a bit abandoned but once my summer starts in a couple of weeks, I'll give it a go at updating and improving the state of the plugin.

**Comment by carrascomj** [comment]
The [new release](https://crates.io/crates/bevy_svg_map/) takes care of this.

Note that there were some changes to the API...
